services:
  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    command: npm run dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - 8000:3000
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432

volumes:
  db-data: